# Generated by Django 3.0.5 on 2020-04-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('A', 'Administrator'), ('N', 'Normal User')], default='N', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_card', models.CharField(max_length=200, null=True)),
                ('player_name', models.CharField(default='', max_length=200)),
                ('set_word', models.CharField(max_length=200, null=True)),
                ('variation', models.CharField(max_length=200, null=True)),
                ('card', models.CharField(max_length=200, null=True)),
                ('grade', models.CharField(max_length=200, null=True)),
                ('terms_include', models.CharField(max_length=255, null=True)),
                ('terms_exclude', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
    ]
